### ISSUE TITLE
Copy button absent in reply messages in groups

### ISSUE THREAD

**Issue by Giando** [bcmapp/bcm-android#1]
In reply messages in groups, you cannot copy another member's reply text.
In new messages, where no other message is listed, you can do it safely.

Thank you,
best regards and Merry Christmas! :santa: 

![BCM-Bug1](https://user-images.githubusercontent.com/8095242/71430201-b4fdc280-26ca-11ea-86b4-9d14b5dda106.png)

**Comment by SneakyPayload** [comment]
You also can’t follow links included in replies.

**Comment by Giando** [comment]
Fixed in v2.7.0 with the addition of d715e8df13234c685cdfc2b3329ada07da0ceb00.

Thank you
