### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by Yoanndp** [bcmapp/bcm-android#2]
It would be very cool if this app was uploaded on F-Droid

**Comment by jwsp1** [comment]
+1 on this. 
I will start using the app if its on F-Droid

**Comment by jwsp1** [comment]
+1 on this.
I will start using the app when it's on F-Droid

**Comment by TNCS-git** [comment]
Think they are understaffed or not focusing on stuff like this yet. Even the git is not the latest build compare to PlayStore. For me this was like 'here we go, what we promised to release the source code'. Was disappointed not finding the server software.
