### ISSUE TITLE
BCM not available on PlayStore anymore 

### ISSUE THREAD

**Issue by jwsp1** [bcmapp/bcm-android#5]
Looks like Google deleted your app on PlayStore. Can't find it and direct link doesn't work anymore.

**Comment by Tamnac** [comment]
https://play.google.com/store/apps/details?id=com.bcm.messenger&hl=en_US

**Comment by jwsp1** [comment]
> https://play.google.com/store/apps/details?id=com.bcm.messenger&hl=en_US

Looks like it's up again. Very odd. Wonder whether that was a mistake by Google or because of something else. Hope bcm will have a fast & transparent support in future, also when their servers are down etc :)
